### ISSUE TITLE
Critical error in DNN 09.04.01

### ISSUE THREAD

**Issue by david-poindexter** [DNNCommunity/DNN.Announcements#38]
## Describe the bug
Critical error in DNN 09.04.01

## Software Versions
- DNN: 09.04.01
- Module: 07.02.01

## To Reproduce
1. Install module in DNN 09.04.01
2. Add module to a page
3. See error in **Manage > Admin Logs**

## Screenshots
n/a

## Error log
```
10/08/2019 01:35:07
Page Load Exception
host 
DNN 09.04.01 
AbsoluteURL /Default.aspx DefaultDataProvider DotNetNuke.Data.SqlDataProvi 
AbsoluteURL:/Default.aspx

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:d6555b79-f859-4ad2-aa0b-01feebc2c789

AssemblyVersion:9.4.1

PortalId:0

UserId:1

TabId:33

RawUrl:/Announcements

Referrer:http://dnn941.loc/Default.aspx?tabid=33&amp;error=Invalid+column+name+%27UrlTrackingInfo%27.&amp;content=0

UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36

ExceptionHash:zGupxnx/h59tkwJv07YNxqtDN3Y=

Message:Invalid column name 'UrlTrackingInfo'.

StackTrace:

InnerMessage:Invalid column name 'UrlTrackingInfo'.

InnerStackTrace:

   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at PetaPoco.Database.<ExecuteReader>d__149`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at DotNetNuke.Modules.Announcements.Components.Business.AnnouncementsController.GetCurrentAnnouncements(Int32 moduleId, DateTime startDate)
   at DotNetNuke.Modules.Announcements.MVP.Presenters.AnnouncementsViewPresenter.GetAnnouncements(Object sender, EventArgs e)
   at DotNetNuke.Modules.Announcements.AnnouncementsView.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
Source:

FileName:

FileLineNumber:0

FileColumnNumber:0

Method:
```

## Additional context
n/a

**Comment by TopCat6** [comment]
I confirm. Just got the same error:  Invalid column name 'UrlTrackingInfo'
```
AbsoluteURL:/dotnetnuke/Default.aspx

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:be874a36-b93d-4ade-8dc1-c85c5aa14151

AssemblyVersion:9.4.1

PortalId:5

UserId:31

TabId:270

RawUrl:/dotnetnuke/inoui/Contact-Us

Referrer:http://localhost/dotnetnuke/inoui

UserAgent:Mozilla/5.0 (Windows NT 10.0; rv:69.0) Gecko/20100101 Firefox/69.0

ExceptionHash:7q2ecUiFjrPWrafncu8lHYFgv8k=

Message:Invalid column name 'UrlTrackingInfo'.

StackTrace:

InnerMessage:Invalid column name 'UrlTrackingInfo'.
```

**Comment by valadas** [comment]
From a quick look, I believe there might be a missing [IgnoreColumn] decorator on this:

https://github.com/DNNCommunity/DNN.Announcements/blob/a8699a872d4f174bd79566a71637cad0f8231e5e/Components/Business/AnnouncementInfo.cs#L177

**Comment by SCullman** [comment]
Taking @valadas findings, I compiled a [package](https://github.com/SCullman/DNN.Announcements/releases/tag/09.04.01) for DNN9.4.1 in my fork. PR is possible if requested.

**Comment by valadas** [comment]
A PR would we awesome @SCullman !

**Comment by mattmol** [comment]
I loaded this https://github.com/SCullman/DNN.Announcements/releases/tag/09.04.01 and it deleted my Announcement Templates.

When I recreated a template, it worked in edit/admin mode. It did not load the custom template in public view.  It seems to load the default template in public view.

**Comment by mattmol** [comment]
Is there a way to fix this without reinstalling the module?

**Comment by SCullman** [comment]
@mattmol .I forked it because I need a fix immediately and I am not not a member of that team here. It looks like there are more bugs in announcement, as you report here. You should then create new issues for that.
Btw, when I do changes in Announcement Templates in my fork, they work in admin mode and in public view, at least for me. Saying that I must admit that I also noticed that changes to "Alternate Item Template" are not stored and remain blank.

**Comment by mattmol** [comment]
Thank you -- I created a new bug report
https://github.com/DNNCommunity/DNN.Announcements/issues/41

**Comment by valadas** [comment]
> I forked it because I need a fix immediately and I am not not a member of that team here

@SCullman would you like to become a maintainer of this module, let me know and I can change your permissions so you can be...

**Comment by Ceten** [comment]
The version @SCullman created seems to solve the issues for me. @valadas is it possible to install this and later update to the new official release? If not I'll have to revert to 9.3.2 and await the final version.

**Comment by mattmol** [comment]
bump

**Comment by Ceten** [comment]
@valadas could you tell us if it's safe to use the version @SCullman created and possible to update to the official release later?

**Comment by SCullman** [comment]
- My version doesn't change the database schema, it just replaces basically the assembly.
- The stupidest thing it does is that the version number of the module will be increased to 9.4.1 to sync with the number with  target DNN framework. If a new release is published here later with a lower version number, you will need to modify this in extensions to a version lower than the new one.
- I can be a bad guy or a bad coder and installing my version might corrupt your setup. You will never know - therefore do a proper backup in advance.

**Comment by jncraig** [comment]
I particularly LOVE the third bullet point!

**Comment by Ceten** [comment]
@SCullman , thanks for your answer! I read what you've changed and saw the pull request. I was mostly worried about the upgrade path regarding the version number because I don't know much about DNN extensions but now I see it can be easily changed in the extensions interface. Also absolutely spot on about the third bullet point!

**Comment by valadas** [comment]
@SCullman if your version does not produce a breaking change or clash with this one, would you like to merge it into this one, I would see no problem bumping the version by a lot to satisfy both people who had this one and yours, just having the core modules in this repository means we have more than a single contributor in case you know someone get's hit by a bus :)
